config/routes.rb
Rails.application.routes.draw do
  resources :faces, only: [:new, :create, :show, :index, :edit, :update, :destroy]

end

app/models/face.rb
class Face < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController

  def index
    @faces = Face.all
  end

  def edit
    @face = Face.find(params[:id])
  end

  def update
    @face = Face.update(params[:id], face_params)
    if @face.save
      redirect_to face_path(@face.id)
    else
    end
  end

  def destroy
    Face.destroy(params[:id])
    redirect_to faces_path
  end

  def new
    @face = Face.new
  end

  def create
    @face = Face.new(face_params)
    if @face.save
      redirect_to face_path(@face.id)
    else
    end
  end

  def show
    @face = Face.find(params[:id])
  end

  private

  def face_params
    params.require(:face).permit(:shape)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/faces/edit.html.erb
<%= form_for(@face) do |f| %>
  <%= f.label :shape %>
  <%= f.text_field :shape %>
  <%= f.submit "Update Face" %>
<% end %>

app/views/faces/index.html.erb
<h1>All faces</h1>

<% @faces.each do |face| %>
  <%= link_to face.shape, face_path(face.id) %>
<% end %>

app/views/faces/new.html.erb
<%= form_for(@face) do |f| %>
  <%= f.label :shape %>
  <%= f.text_field :shape %>
  <%= f.submit "Create Face" %>
<% end %>

app/views/faces/show.html.erb
<h1>face show page</h1>

<p>Shape: <%= @face.shape %><p>

<%= link_to "Edit", edit_face_path(@face.id) %><br>
<%= link_to "Delete Face", face_path(@face.id), method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FaceCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>